name: food_ordering_project
services:
  db:
    image: postgres:17-alpine
    container_name: food_ordering_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_APP_USER=${POSTGRES_APP_USER}
      - POSTGRES_APP_PASSWORD=${POSTGRES_APP_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./_entrypoint:/docker-entrypoint-initdb.d
    networks:
      - food_ordering_network
    restart: unless-stopped

volumes:
  db_data:
networks:
  food_ordering_network:
